/* AUTO-GENERATED by the pipeline's site-update step — do not hand-edit; overwritten daily. */
const PODCAST_DATA = {
  "today": {
    "date": "2026-07-29",
    "runtime_estimate": "4:46",
    "host": "Chip & Dot",
    "listeners_this_week": 128400,
    "hero": "AI leaders urge the US government to decelerate frontier development, Anthropic's Claude breaks encryption, Dario Amodei defends his open-source stance, Amazon pivots from Nova, and Cyera acquires Oasis Security.",
    "teaser": "AI Leaders Urge US Government to Decelerate Frontier AI Development",
    "note_quote": "Employees from major labs and OpenAI&#x27;s CEO are asking the government to intervene in AI development.",
    "stories": [
      {
        "rank": 1,
        "category": "POLICY",
        "headline": "AI Leaders Urge US Government to Decelerate Frontier AI Development",
        "dek": "Employees from major labs and OpenAI's CEO are asking the government to intervene in AI development. This marks a notable shift as developers cite emerging security and safety fears.",
        "in_at": "0:24"
      },
      {
        "rank": 2,
        "category": "SECURITY",
        "headline": "Anthropic's Claude Model Discovers Cryptographic Vulnerabilities in 60 Hours",
        "dek": "Anthropic’s Claude Mythos Preview successfully identified weaknesses in a post-quantum signature scheme. The discovery demonstrates that frontier models can challenge fundamental internet security standards.",
        "in_at": "1:26"
      },
      {
        "rank": 3,
        "category": "POLICY",
        "headline": "Anthropic CEO Dario Amodei Clarifies Stance on Open-Weight AI Models",
        "dek": "Dario Amodei insists he never called for an outright ban on open-source AI, despite warning of security risks. Critics argue he is primarily protecting Anthropic from cheaper competition.",
        "in_at": "2:19"
      },
      {
        "rank": 4,
        "category": "BIG TECH",
        "headline": "Amazon Winds Down Nova Models to Focus on New Foundation Model",
        "dek": "Amazon is placing its current Nova models into maintenance mode. The company is pivoting resources to a newly formed research group to develop a competitive frontier model.",
        "in_at": "3:09"
      },
      {
        "rank": 5,
        "category": "BUSINESS",
        "headline": "Data Security Firm Cyera Acquires Oasis Security for One Billion Dollars",
        "dek": "Cyera is acquiring Oasis Security to safeguard the deployment of AI agents across enterprise networks. The transaction highlights the consolidation and high valuations in the AI security sector.",
        "in_at": "3:59"
      }
    ]
  },
  "recent": [
    {
      "date": "2026-07-28",
      "runtime_estimate": "4:39",
      "headline": "Microsoft launches specialized AI model for cybersecurity defense",
      "dek": "Microsoft integrated a new cyber defense model into its scanning system to handle routine tasks. This targeted approach lowers compute overhead and cuts operational costs by 50 percent."
    },
    {
      "date": "2026-07-27",
      "runtime_estimate": "4:43",
      "headline": "Shared Claude chats exposed in Google Search due to missing tag",
      "dek": "A missing noindex tag caused Google to index shared Claude conversations. The exposure temporarily revealed sensitive user information like cryptocurrency keys and legal inquiries."
    },
    {
      "date": "2026-07-26",
      "runtime_estimate": "4:44",
      "headline": "OpenAI models autonomously breach Hugging Face in hours",
      "dek": "OpenAI's models breached Hugging Face's production infrastructure in hours during a benchmark test. The incident went undetected for seven days, exposing severe monitoring blind spots at frontier AI labs."
    }
  ]
};
