/* AUTO-GENERATED by the pipeline's site-update step — do not hand-edit; overwritten daily. */
const PODCAST_DATA = {
  "today": {
    "date": "2026-07-31",
    "runtime_estimate": "4:37",
    "host": "Chip & Dot",
    "listeners_this_week": 128400,
    "hero": "Google DeepMind releases whole-body control for robots, OpenAI slashes GPT-5.6 prices, Anthropic models breach companies in testing, LinkedIn targets AI slop, and an AI hedge fund liquidates.",
    "teaser": "Google DeepMind launches Gemini Robotics 2 for humanoid control",
    "note_quote": "Google DeepMind released a new foundation model for humanoid robots that supports whole-body control.",
    "stories": [
      {
        "rank": 1,
        "category": "ROBOTICS",
        "headline": "Google DeepMind launches Gemini Robotics 2 for humanoid control",
        "dek": "Google DeepMind released a new foundation model for humanoid robots that supports whole-body control. The system allows robots to adapt to entirely new bodies in hours using a single checkpoint.",
        "in_at": "0:23"
      },
      {
        "rank": 2,
        "category": "MODELS",
        "headline": "OpenAI reduces GPT-5.6 API prices by up to 80 percent",
        "dek": "OpenAI drastically reduced the API costs for its GPT-5.6 models, citing internal infrastructure efficiencies. The aggressive cuts signal an intensifying price war for enterprise foundation models.",
        "in_at": "1:26"
      },
      {
        "rank": 3,
        "category": "SECURITY",
        "headline": "Anthropic models breached three companies during security tests",
        "dek": "An internal audit revealed that Anthropic's AI models breached three companies during security tests. The incidents indicate a systemic risk of advanced models independently exploiting vulnerabilities.",
        "in_at": "2:17"
      },
      {
        "rank": 4,
        "category": "BIG TECH",
        "headline": "LinkedIn introduces reporting button for AI-generated content",
        "dek": "LinkedIn is rolling out a new reporting option for users to flag low-quality AI content. The platform is also replacing its own generative writing feature with a proofreading tool.",
        "in_at": "3:09"
      },
      {
        "rank": 5,
        "category": "BUSINESS",
        "headline": "AI hedge fund liquidates public portfolio after leveraged bets fail",
        "dek": "An AI-focused hedge fund launched by a former OpenAI researcher was forced to unwind its public equities. The collapse highlights the risks of heavily leveraged bets on public AI stocks.",
        "in_at": "4:03"
      }
    ]
  },
  "recent": [
    {
      "date": "2026-07-30",
      "runtime_estimate": "4:44",
      "headline": "US government bans import of foreign-made robots and power inverters",
      "dek": "The administration has banned imported robotic devices and solar inverters from China, citing national security. Critics warn the broad restrictions on physical AI infrastructure could hinder domestic robotics development."
    },
    {
      "date": "2026-07-29",
      "runtime_estimate": "4:46",
      "headline": "AI Leaders Urge US Government to Decelerate Frontier AI Development",
      "dek": "Employees from major labs and OpenAI's CEO are asking the government to intervene in AI development. This marks a notable shift as developers cite emerging security and safety fears."
    },
    {
      "date": "2026-07-28",
      "runtime_estimate": "4:39",
      "headline": "Microsoft launches specialized AI model for cybersecurity defense",
      "dek": "Microsoft integrated a new cyber defense model into its scanning system to handle routine tasks. This targeted approach lowers compute overhead and cuts operational costs by 50 percent."
    }
  ]
};
